services:
  jabba-ai-ui:
    container_name: jabba-ai-ui
    image: jabba-ai/ui
    build:
      context: .
      dockerfile: deploy/Dockerfile
      target: runner
    restart: unless-stopped
    ports:
      - "3000:3000"
    extra_hosts:
      - "jabba-ai-chat-identity:host-gateway"
      - "jabba-ai-chat-orchestrator:host-gateway"
      - "jabba-ai-chat-session:host-gateway"
      - "jabba-ai-bot:host-gateway"
    networks:
      - jabba-ai-api-bot
    environment:
      - NODE_ENV=production
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - IDENTITY_URL=http://jabba-ai-chat-identity:20000
      - CHAT_ORCHESTRATOR_URL=http://jabba-ai-chat-orchestrator:20001
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  jabba-ai-api-bot:

volumes:
  logs:
    driver: local