<script setup lang="ts">
definePageMeta({
  middleware: 'auth'
})

const router = useRouter()
const { createApplication } = useCreateApplications();

// Form state
const form = ref({
  name: ''
})

const isLoading = ref(false)
const error = ref('')
const success = ref(false)


// Form validation
const isFormValid = computed(() => {
  return form.value.name.trim().length > 0
})

const goBack = () => {
  router.push('/dashboard/application/list')
}

const sendCreateApplicationRequest = async () => {
  if (!isFormValid.value) return

  isLoading.value = true
  error.value = ''

  try {
    await createApplication(form.value.name);
    success.value = true

    // Redirect back to applications after a short delay
    setTimeout(() => {
      router.push('/dashboard/application/list')
    }, 1500)

  } catch (err) {
    error.value = 'Failed to create application. Please try again.'
    console.error('Error creating application:', err)
  } finally {
    isLoading.value = false
  }
}

const handleSubmit = (e: Event) => {
  e.preventDefault()
  sendCreateApplicationRequest()
}
</script>

<template>
  <div class="mt-8">
    <div class="container mx-auto px-4 max-w-2xl">
      <!-- Header -->
      <div class="flex items-center justify-between mb-8">
        <h1 class="text-2xl font-bold text-white">Create New Application</h1>
        <button
            @click="goBack"
            class="px-4 py-2 bg-white/10 text-white rounded-lg hover:bg-white/20 transition-colors"
        >
          ← Back to Applications
        </button>
      </div>

      <!-- Success Message -->
      <div v-if="success" class="mb-6 p-4 bg-green-500/10 border border-green-500/30 rounded-lg">
        <div class="flex items-center gap-2">
          <span class="text-green-400">✓</span>
          <span class="text-green-400 font-medium">Application created successfully!</span>
        </div>
        <p class="text-green-300/70 text-sm mt-1">Redirecting to applications...</p>
      </div>

      <!-- Error Message -->
      <div v-if="error" class="mb-6 p-4 bg-red-500/10 border border-red-500/30 rounded-lg">
        <div class="flex items-center gap-2">
          <span class="text-red-400">✗</span>
          <span class="text-red-400 font-medium">{{ error }}</span>
        </div>
      </div>

      <!-- Form -->
      <div class="bg-white/10 rounded-lg backdrop-blur-sm border border-white/20 p-6">
        <form @submit="handleSubmit">
          <div class="mb-6">
            <label for="applicationName" class="block text-white font-medium mb-2">
              Application Name *
            </label>
            <input
                id="applicationName"
                v-model="form.name"
                type="text"
                placeholder="Enter application name"
                class="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white placeholder-white/50 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                :disabled="isLoading || success"
                required
            />
            <p class="text-white/50 text-sm mt-1">
              Choose a descriptive name for your application
            </p>
          </div>

          <div class="flex gap-4">
            <button
                type="submit"
                :disabled="!isFormValid || isLoading || success"
                class="flex-1 px-6 py-3 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors flex items-center justify-center gap-2"
            >
              <span v-if="isLoading" class="animate-spin">⟳</span>
              <span v-else-if="success">✓</span>
              <span v-else>+</span>

              <span v-if="isLoading">Creating...</span>
              <span v-else-if="success">Created!</span>
              <span v-else>Create Application</span>
            </button>

            <button
                type="button"
                @click="goBack"
                :disabled="isLoading"
                class="px-6 py-3 bg-white/10 hover:bg-white/20 disabled:bg-gray-600 disabled:cursor-not-allowed text-white font-medium rounded-lg transition-colors"
            >
              Cancel
            </button>
          </div>
        </form>
      </div>

      <!-- Info Box -->
      <div class="mt-6 p-4 bg-blue-500/10 border border-blue-500/30 rounded-lg">
        <div class="flex items-start gap-2">
          <span class="text-blue-400 mt-0.5">ℹ</span>
          <div>
            <h3 class="text-blue-400 font-medium">Application Creation</h3>
            <p class="text-blue-300/70 text-sm mt-1">
              Only the application name is required. All other details like ID, creation date, and configuration will be automatically generated by the system.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
</style>